In [1]:
import numpy as np
import scipy as scp

In [2]:
A = np.array([[2, 3, 4], [-1, -2, -3], [0, 0, 1]])

In [9]:
scp.linalg.lu(A, permute_l=True)

(array([[ 1. ,  0. ,  0. ],
        [-0.5,  1. ,  0. ],
        [ 0. , -0. ,  1. ]]),
 array([[ 2. ,  3. ,  4. ],
        [ 0. , -0.5, -1. ],
        [ 0. ,  0. ,  1. ]]))

In [11]:
scp.linalg.solve(A, b=np.array([1, -1, 1]))

array([ 0., -1.,  1.])

In [12]:
np.linalg.solve(A, b=np.array([1, -1, 1]))

array([ 0., -1.,  1.])

In [13]:
scp.linalg.cholesky(np.array([[1, 3], [3, 25]]))

array([[1., 3.],
       [0., 4.]])

In [14]:
np.array([[1/3, -2/3, 2/3], 
         [-2/3, -2/3, -1/3],
         [2/3, -1/3, -2/3]]) @ np.array([[1, -1, 5],
                                        [-2, 0, -3], 
                                        [2, -1, -7]])

array([[ 3., -1., -1.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  9.]])

In [15]:
scp.linalg.qr(np.array([[1, -1, 5], 
                        [-2, 0, -3], 
                        [2, -1, -7]]))

(array([[-0.33333333,  0.66666667, -0.66666667],
        [ 0.66666667,  0.66666667,  0.33333333],
        [-0.66666667,  0.33333333,  0.66666667]]),
 array([[-3.,  1.,  1.],
        [ 0., -1., -1.],
        [ 0.,  0., -9.]]))

In [28]:
np.array([[(-1+1j)/6**(1/2), 0, (1-1j)/3**(1/2)],
         [2*1j/6**(1/2), 0, 1j/3**(1/2)],
         [0, 1, 0]]) @ np.array([[1/3, 0, 0], 
                                 [0, 1/3, 0], 
                                 [0, 0, 0]]) @ np.matrix([[(-1+1j)/6**(1/2), 0, (1-1j)/3**(1/2)],
         [2*1j/6**(1/2), 0, 1j/3**(1/2)],
         [0, 1, 0]]).H

matrix([[0.11111111+0.j        , 0.11111111+0.11111111j,
         0.        +0.j        ],
        [0.11111111-0.11111111j, 0.22222222+0.j        ,
         0.        +0.j        ],
        [0.        +0.j        , 0.        +0.j        ,
         0.33333333+0.j        ]])

In [31]:
a = np.matrix([[1, 2, 3],
              [1, 2, 3]]).T

In [33]:
1/14**(1/2)

0.2672612419124244

In [32]:
scp.linalg.svd(a)

(array([[-0.26726124,  0.95618289,  0.11952286],
        [-0.53452248, -0.04390192, -0.84401323],
        [-0.80178373, -0.28945968,  0.52283453]]),
 array([5.29150262e+00, 7.02166694e-16]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [34]:
A = np.array([[7, 1, 2],
         [5, 5, 2],
         [3, 3, 6],
         [1, 7, 2]])

In [35]:
A.T@A

array([[84, 48, 44],
       [48, 84, 44],
       [44, 44, 48]])